### ISSUE TITLE
Wechaty Puppet Service Provider FAQ

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-services#1]
### 1. What is Wechaty Puppet Service Provider

to be written

See: [Wechaty OSS Project and the Commercial Puppet Service Provider (CPSP)](https://github.com/wechaty/PMC/issues/11)

### 2. What is Wechaty Puppet Service Token

to be written

To use the token with Wechaty, the following commands demonstrated how to use it under Linux/macOS:

```shell
export WECHATY_PUPPET_HOSTIE_TOKEN=your_applied_token_at_here

WECHATY_PUPPET=wechaty-puppet-hostie node bot.js
```

See:

1. [Wechaty Starter Project Template that works out-of-the-box](https://github.com/wechaty/wechaty-getting-started)
1. [How to create your own Wechaty Hostie Token with the Web Protocol](https://github.com/wechaty/wechaty/issues/1986)

## If you are a Wechaty Puppet Service Provider

Please feel free to list yourself to our list, and add your introduction in this README by submitting a Pull Request!

## If you want to become a Wechaty Puppet Service Provider

Please do not hesitate to file an issue to introduce yourself in this repository, then contact us at <https://gitter.im/wechaty/wechaty>!

## Apply for the token

Please submit your application by filing an issue at <https://github.com/wechaty/puppet-service-providers/issues/new/choose>

**Comment by wordgao** [comment]
介绍自己（您是谁）：
wordgao。免费的开发人员。
解释您要解决的问题：（您的工作）：
构建一个聊天机器人
您的机器人与以下任务相关吗？（是/否）
否
攻击与性行为
否
您的电子邮件：
wordgao@163.com
您的微信：
wordgao
我已经通过README.md的QR Code加入了Wechaty开发人员之家的Wechat聊天室：（如果不是，请加入论坛，然后说是在这里）
是
我知道Wechaty Puppet Donut处于Alpha初期，我拥有必要的工程技术来处理错误，而不仅仅是寻求支持：（请说是，然后在此处输入您的姓名）wordgao
是

**Comment by huan** [comment]
@wordgao Please submit your apply by filing an issue at <https://github.com/wechaty/puppet-service-providers/issues/new/choose>
