### ISSUE TITLE
PadLocal: 我按照https://wechaty.js.org/docs/puppet-services/diy/中，step6里步骤配置docker，服务器端无限显示以下内容，请求帮助

### ISSUE THREAD

**Issue by sunyidi123** [wechaty/puppet-services#104]
09:59:54 VERB [Request] [tid:abea198a] receive event from server, seq:13 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"e1aabdbcceb9445da5a1e1e4b7aa6fca","longlinkid":"","initphase":false}}
09:59:54 VERB [Request] [tid:f8efd1b9] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"5e0a41dc99984eb19380b36214a511e5","messageid":"e1aabdbcceb9445da5a1e1e4b7aa6fca"}
09:59:54 VERB [Request] [tid:f8efd1b9] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDAVkJJksXI+JmyKBD9YyyY8Wl5RlQw9E9pVJPkvfkN9NF8VfccvzeThBFRn7AbvFkbA4DFy2RXjVs8AExuDEi5q9ho746suxFyKNMCwAzVqvwLMFISzfnk49rS6J9lcVH9VoLYREivgwFPIK42gT+q/Ljogdike9cFaaEvWJk6Yd8/BBThuOLqB2GpYEbhfjzOweWzZsuaPWO+Wqh56gpxfPinTuuO7ffN6P9ls9vf3nO1hCnzh82IEddWnNA0//CORKbTUGySVBXca0wZIdwH03Mfs7wMS5S7jS/nzwM7/e/Z0y88NHoi4JajXDxy0QqfuwUuIFk1HZAziid+/M2zjZFEfUPmYHrqLgAGlxbHLpTR0ydNXyLfITeClTc2uaURwxyuPPiEPGnVC9AixudcDaDy1+3cwRK8meNdmxpldDSue34+/XwuuhUud2++EP16ThxmT8kQ7pARjs="}
09:59:54 VERB [LongLink] [5e0a41dc99984eb19380b36214a511e5] socket send:17f103015909264b1723e266c8a043f58cb263c5a5e51950c3d13da5524f92f7e437d345f157dc72fcde4e1045467ec06ef1646c0e03172d915e356cf00131b83122e6af61a3be3ab2ec45c8a34c0b003356abf02cc1484b37e7938f6b4ba27d95c547f55a0b611122be0c053c82b8da04feabf2e3a2076291ef5c15a684bd6264e9877cfc105386e38ba81d86a5811b85f8f33b0796cd9b2e68f58ef96aa1e7a829c5f3e29d3bae3bb7df37a3fd96cf6f7f79ced610a7ce1f3620475d5a7340d3ffc239129b4d41b249505771ad306487701f4dcc7ecef0312e52ee34bf9f3c0ceff7bf674cbcf0d1e88b825a8d70f1cb442a7eec14b88164d47640ce289dfbf336ce364511f50f9981eba8b8001a5c5b1cba53474c9d357c8b7c84de0a54dcdae694470c72b8f3e210f1a7542f408b1b9d703683cb5fb773044af2678d766c6995d0d2b9edf8fbf5f0bae854b9ddbef843f5e93871993f2443ba40463b
09:59:54 VERB [LongLink] [5e0a41dc99984eb19380b36214a511e5] socket recv:17f10301386a0abdd66e69fb41b48b275a5db3176f99bfec84d2e8b8831770fa0acbc0ab7cf202de7fdf2739e84fa6897dde8a18b4bef352386f7374a08ab349007c114dbeb0d0da1a279127bf04fa00c7b7b5a0205a4d4ee402d6af30e118bac8e1eaab8c6aed445e55604f008ab6253849ffb9e69dd0780729abee36292c4fbf5e595c8823feb9d3de8d83c90282eb5d533525e1ee1bd86e7bc0c52266496a83d5d86e055df5fa19c5c466ccb7f2f0d348fd6a37caede19ab8a5573adfa3279c9abc0d930300ded31010c45ead7806809861a937a46d3f02e23b123bdf450563ef2f0385e7fb5e0a9db5e945b70f9ceb885c9b9a76a600fe1ab5b617e946e25437f0c1bef7ede42c5681f130ae3094b226f4781e65127960fff7c6d3aaf7eb72619464d4bd86d067d9edb4ff2518385e752ea376b90b04af3e4f57c3
09:59:54 VERB [Request] [tid:45ede105] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"5e0a41dc99984eb19380b36214a511e5","payload":"F/EDAThqCr3Wbmn7QbSLJ1pdsxdvmb/shNLouIMXcPoKy8CrfPIC3n/fJznoT6aJfd6KGLS+81I4b3N0oIqzSQB8EU2+sNDaGieRJ78E+gDHt7WgIFpNTuQC1q8w4Ri6yOHqq4xq7UReVWBPAIq2JThJ/7nmndB4Bymr7jYpLE+/XllciCP+udPejYPJAoLrXVM1JeHuG9hue8DFImZJaoPV2G4FXfX6GcXEZsy38vDTSP1qN8rt4Zq4pVc636MnnJq8DZMDAN7TEBDEXq14BoCYYak3pG0/AuI7EjvfRQVj7y8Dhef7XgqdtelFtw+c64hcm5p2pgD+GrW2F+lG4lQ38MG+9+3kLFaB8TCuMJSyJvR4HmUSeWD/98bTqvfrcmGUZNS9htBn2e20/yUYOF51LqN2uQsErz5PV8M="}
09:59:55 VERB [Request] [tid:45ede105] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"e1aabdbcceb9445da5a1e1e4b7aa6fca"}]}
09:59:55 VERB [Request] [tid:abea198a] send event to server, seq:undefined, ack:13, type: 11, payload: {"longlinkresponse":{}}

![image](https://user-images.githubusercontent.com/56663564/113278481-8da59480-9314-11eb-909e-bc2ce7015849.png)

**Comment by padlocal** [comment]
看上去没什么错误，是因为比较多的“无意义的” debug 日志让你觉得不爽吗？

**Comment by sunyidi123** [comment]
emmm。。。我只是感觉并没有在正常工作，因为我已经等了20分钟，依然是在重复这些内容

**Comment by padlocal** [comment]
可以按照这里：https://wechaty.js.org/docs/puppet-services/diy/#5-set-wechaty-log-level  把 loglevel  修改为 info，可能会让你感觉舒适一些。
