### ISSUE TITLE
PadLocal: Applying for a PadLocal token.

### ISSUE THREAD

**Issue by slatdude** [wechaty/puppet-services#107]
Please make sure you have read the [Wechaty Puppet Service: PadLocal](https://wechaty.js.org/docs/puppet-services/padlocal/) from Wechaty Official Website before you continue writting this issue.

## Question
I am a student majoring in cyber security. I am applying for a PadLocal Token to implement the term project related on Content Security. It is about sensitive content filtering and we need a Wechat API to effectively present our project. We are willing to share our code after finishing the project.

**Comment by padlocal** [comment]
You can apply here: http://pad-local.com
