### ISSUE TITLE
JuziBot Puppet Service 系统升级通知

### ISSUE THREAD

**Issue by lijiarui** [wechaty/puppet-services#11]
亲爱的开发者，您好！

为了更好的提供服务，JuziBot Puppet Service 计划于11月30日进行一次 wechaty-puppet-padplus 重大升级。

如您正在使用 wechaty-puppet-padplus服务, 则需要进行如下升级操作。（如未使用 wechaty-puppet-padplus,可安全的忽视本通知）

wechaty-puppet-padplus 升级说明如下:
1. 卸载 wechaty-puppet-padplus, 安装 wechaty-puppet-hostie
2. 代码中启动wechaty的 wechaty-puppet-padplus 更换成 wechaty-puppet-hostie
3. 更换 padplus token，替换成wechaty-puppet-donut或者wechaty-puppet-wxwork的token

详细说明：
wechaty-puppet-padplus 将会在11月30日下线，已付费的用户可以升级到下面的两个puppet:
1. wechaty-puppet-donut: 基于 windows 的个人微信，除了 padplus 的基础功能外，还支持接受企业微信消息，详细信息见 https://github.com/juzibot/donut-tester
2. wechaty-puppet-wxwork: 基于 windows 客户端的企业微信，详细信息见 https://github.com/juzibot/wxwork-tester

如在11月30日前没有升级代码库，wechaty-puppet-padplus 服务将会在12月1日00:00停止服务，导致您托管的微信不可用，所以强烈建议提前进行代码升级，以避免机器人意外终止服务。

如果您有任何问题，请及时与我们的客服联系，微信：`juzibot`

**Comment by huan** [comment]
Please publish this announcement to the padplus repo README so that the developers who are go to there can get this information.

Also I'd like to archive the padplus repo as well.

**Comment by wordgao** [comment]
![Uploading image.png…]()

**Comment by smwsk** [comment]
那是不是以后就用不了ipad协议了、只有donut的windows协议而已

**Comment by Mr-jiao** [comment]
升级需要更换token吗

**Comment by ZakaryCode** [comment]
It doesn't work for me at the moment. Using the official test will also prompt a "failed to connect to all addresses" error, hope to avoid invalid debugging by providing a method to eliminate service problems.

```ts
// Test Code
import { Wechaty } from 'wechaty';
import { ScanStatus } from 'wechaty-puppet';
import QrcodeTerminal from 'qrcode-terminal';

const token = 'puppet_donut_b7688931d26ab0fb';

const bot = new Wechaty({
  puppet: 'wechaty-puppet-hostie',
  puppetOptions: {
    token,
  },
});

bot
  .on('scan', (qrcode, status) => {
    if (status === ScanStatus.Waiting) {
      QrcodeTerminal.generate(qrcode, {
        small: true,
      });
    }
  })
  .on('login', async (user) => {
    console.log(`user: ${JSON.stringify(user)}`);
  })
  .on('message', async (message) => {
    console.log(`message: ${JSON.stringify(message)}`);
  })
  .start();
```
![image](https://user-images.githubusercontent.com/24262362/99871260-e1d89380-2c13-11eb-9587-ae30e5605dc3.png)

**Comment by huan** [comment]
@ZakaryCode Your token should not be posted in your issue. (please contact your provider to make a new one)

For anyone who wants to confirm that your token is online, please visit `http://api.chatie.io/v0/hosties/YOUR_TOKEN` to check the return value includes the `ip` and `port` value like the following:

```json
{
  "ip":"1.2.3.4",
  "port":1234
}
```

If the `port` is `0` then that means your token is not online for service, please contact your Wechaty puppet service provider.

**Comment by ZakaryCode** [comment]
> @ZakaryCode Your token should not be posted in your issue. (please contact your provider to make a new one)
> 
> For anyone who wants to confirm that your token is online, please visit `http://api.chatie.io/v0/hosties/YOUR_TOKEN` to check the return value includes the `ip` and `port` value like the following:
> 
> ## `http://api.chatie.io/v0/hosties/YOUR_TOKEN`
> ```json
> {
>   "ip":"1.2.3.4",
>   "port":1234
> }
> ```
> 
> If the `port` is `0` then that means your token is not online for service, please contact your Wechaty puppet service provider.

Sorry, I didn't realize it when I submitted it. Thanks for reminding

**Comment by fanchunke1991** [comment]
wechaty token gate server 上使用了 wechaty-puppet-padplus，请问这个要如何升级？

**Comment by huan** [comment]
> wechaty token gate server 上使用了 wechaty-puppet-padplus，请问这个要如何升级？

You can use the new token (donut / wxwork) directly after the upgrade.

The token gateway is not needed anymore for the donut/wxwork tokens.

Link to https://github.com/wechaty/wechaty/issues/1985

**Comment by fanchunke1991** [comment]
> > wechaty token gate server 上使用了 wechaty-puppet-padplus，请问这个要如何升级？
> 
> You can use the new token (donut / wxwork) directly after the upgrade.
> 
> The token gateway is not needed anymore for the donut/wxwork tokens.
> 
> Link to [wechaty/wechaty#1985](https://github.com/wechaty/wechaty/issues/1985)

明白了，非常感谢。

不过在 Python 中修改了新的 donut token 以后，遇到一个很奇怪的问题：用户发送消息A给 bot，bot 回复消息B后，bot 会开始发送上一次的消息 B 给自己，之后开始自问问答。

**Comment by huan** [comment]
That's a expected behavior for all Wechaty bots:

You still receive the message that you send from yourself, just like the Wechat client.

What you need to do is use `msg.self()` to get to know whether the message is sent by yourself.

**Comment by zhihuifanqiechaodan** [comment]
hi，我想知道此次更新是否有将@所有人和@机器人的区分。

**Comment by fanchunke1991** [comment]
> That's a expected behavior for all Wechaty bots:
> 
> You will receive the message that you send from yourself, just like the Wechat client.
> 
> What you need to do is use `msg.self()` to get to know whether the message is sent by yourself.

wow，got it, thanks.

**Comment by huan** [comment]
@fanchunke1991 You are welcome!

**Comment by Edward-Zhou** [comment]
@huan  Will this affect `wechaty-puppet-donut`? Based on init post, it seems this should not.

But I just found, I got error `WARN No endpoint when starting grpc client`. 

If I access `https://api.chatie.io/v0/hosties/puppet_donut_xxx`, it will only return `{"ip":"0.0.0.0","port":0}`.

Has my puppet_donut token expired？

**Comment by huan** [comment]
> Will this affect wechaty-puppet-donut? Based on init post, it seems this should not.

No, this will not affect the donut.

> If I access https://api.chatie.io/v0/hosties/puppet_donut_xxx, it will only return {"ip":"0.0.0.0","port":0}.

Then it seems that this token is not valid anymore.

**Comment by Edward-Zhou** [comment]
@huan  Could you share how can renew my puppet donut token?

**Comment by huan** [comment]
You can file an new issue in this repo with the right type of your service type, then write your renew apply in the issue.

It will be assigned automatically to the related Wechaty Puppet Service Provider.
