### ISSUE TITLE
ERR_SEND_MSG_TIMEOUT send message timeout, conversationId: R:10696051448037197

### ISSUE THREAD

**Issue by tate4482** [wechaty/puppet-services#116]
Please make sure you have read the [Wechaty Puppet Service: Donut](https://wechaty.js.org/docs/puppet-services/donut/) from Wechaty Official Website before you continue writting this issue.

## Question
ERR_SEND_MSG_TIMEOUT send message timeout, conversationId: R:10696051448037197

**Comment by lijiarui** [comment]
duplicate with #115
