### ISSUE TITLE
MemoryCard support: required for stateless puppet service

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-services#16]
When a Wechaty bots logged in, it will have a authorized secret data to store their logged-in session, for example, the device information (62 data for pad protocol), the cookie (if you are using the web protocol), and the user session secrets, etc.

The [memory card](https://github.com/huan/memory-card) is a module designed to store those data.

## Wechaty bot login with memory card module

1. wechaty start()
1. wechaty instanciates memory card (see [wechaty.ts:start()](https://github.com/wechaty/wechaty/blob/30c446b2b78c92166a1d613952e77d3e3fdbbe1f/src/wechaty.ts#L681))
1. wechaty set memory card to puppet (see [wechaty.ts:initPuppet()](https://github.com/wechaty/wechaty/blob/30c446b2b78c92166a1d613952e77d3e3fdbbe1f/src/wechaty.ts#L406))
    1. puppet start()
    1. puppet load session from memory card
    1. puppet logged in
        1. by loaded session, or
        1. by scan qr code
    1. puppet save the session secret data to memory card
1. memory card will be saved to file or network storage for future reuse

## Conclusion

By saving the user login session secret data to memory card, the Wechaty system can save the state to local, so that it can make the puppet service provider service stateless.

Current neither of the Donut, WXWork, Rock, PadLocal have not support this stateless feature, nor the Wechaty system are ready for it.

To be implemented for our ecosystem.

**Comment by jcai** [comment]
Nice feature
