### ISSUE TITLE
PadLocal: can not login after scan the QR code if the IP is not in China

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-services#62]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

## Question

According to my today's test, and confirmed with the author of PadLocal @padlocal , we get to know that:

> Currently, the PadLocal puppet service can only be used on a server with a China IP address.

To be fixed.

**Comment by padlocal** [comment]
Fixed.
