### ISSUE TITLE
PadLocal: Apply for new token

### ISSUE THREAD

**Issue by mesoar** [wechaty/puppet-services#64]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

**Comment by padlocal** [comment]
@mesoar please send a short email to oxddoxdd#gmail.com, then token related info will be sent to you.
