### ISSUE TITLE
PadLocal: 

### ISSUE THREAD

**Issue by huwei1024** [wechaty/puppet-services#66]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

## Question
Hello, I want to apply a wechaty token.And I'm willing to be involved in open source work. thanks a lot.

**Comment by padlocal** [comment]
@huwei1024 Could you send an email to oxddoxdd#gmail.com ? Then I can send you related materials.
