### ISSUE TITLE
PadLocal:

### ISSUE THREAD

**Issue by wangdahoo** [wechaty/puppet-services#68]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

## Question

Hi, I wanna apply a token for my customer service bot development. Happy to be helpful with related open source stuff later.

**Comment by padlocal** [comment]
@wangdahoo Could you send an email to oxddoxdd#gmail.com ? Then I can send you related materials.

**Comment by wangdahoo** [comment]
@padlocal sent to oxddoxdd@gmail.com
