### ISSUE TITLE
PadLocal: token application

### ISSUE THREAD

**Issue by MachengShen** [wechaty/puppet-services#69]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

## Question
Hi, I would like to apply for a puppet token for developing my chatbot. Please let me know what are the requirements. Thanks!

**Comment by padlocal** [comment]
@MachengShen Could you send an email to oxddoxdd#gmail.com ? Then  I can send you related materials.
