### ISSUE TITLE
PadLocal: 我想购买token应该怎么购买呢

### ISSUE THREAD

**Issue by SessionKey** [wechaty/puppet-services#71]
## Wechaty Puppet PadLocal

- Repo: <https://github.com/padlocal/wechaty-puppet-padlocal>
- Provider: [PadLocal](https://github.com/padlocal)
- Support: <https://github.com/padlocal/wechaty-puppet-padlocal/issues>

**Comment by padlocal** [comment]
Please send email to oxddoxdd#gmail.com
