### ISSUE TITLE
Using PadLocal Token with Polyglot Wechaty via Token Gateway

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-services#84]
## ⬇️ The following docs will not be updated anymore.

For using a PadLocal Token with Polyglot Wechaty other than TypeScript, we need to run the Token Gateway.

It seems we have serval issue reports from our developers who are trying to do this.

The issue might be related to the Polyglot Wechaty, or PadLocal, or the Token Gateway.

In order to track all of them, we create this issue as the top reference.

All related issues will link to this one for future investigation.

### Links

1. https://github.com/wechaty/wechaty/discussions/1985

**Comment by biofer** [comment]
I have a padlocal token. And I have successfully run a Wechaty Token Gate Server with this token. 
when I run python-wechaty-getting-started, it did not work. 
https://github.com/wechaty/wechaty/discussions/1985#discussioncomment-317552

I konw 《6行命令启动一个 .NET Wechaty 服务》

 ```
var PuppetOptions = new PuppetOptions()
{
    Token = "0c7b8f97-f3cc-40a5-a537-d492fd689801",
    Endpoint = "192.168.1.100:9004"
};
 bot = new Wechaty.Wechaty(PuppetOptions);

 await bot.OnScan(WechatyScanEventListener)
     .OnLogin(WechatyLoginEventListener)
     .OnMessage(WechatyMessageEventListenerAsync)
     .OnHeartbeat(WechatyHeartbeatEventListener)
     .Start();
```
So，how set Token  and Endpoint in python-wechaty, Do you mind to offer a example.
THS!

**Comment by huan** [comment]
@biofer According to our [Python Wechaty Getting Started](https://github.com/wechaty/python-wechaty-getting-started/edit/master/README.md) repo:

```sh
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN=your_token_at_here

python examples/ding-dong-bot.py
```

The above should be able to run your Python Wechaty BOT with your Token Gateway.

P.S. the `Endpoint` should not be necessary if you are using a public server.

**Comment by biofer** [comment]
@huan Thank you for your answer。
I followed the instructions，but somethings was wrong.
First, I updated the software.
```
pip install --upgrade
```
Then run Python Wechaty BOT with Token Gateway.

**Comment by huan** [comment]
@biofer Yes, if you are set up a token gateway in an intranet, then you need to specify `WECHATY_PUPPET_SERVICE_ENDPOINT` because the registered IP can not reach your token gateway.

See: https://github.com/wechaty/python-wechaty-puppet-service/blob/master/src/wechaty_puppet_service/config.py#L25

**Comment by biofer** [comment]
@huan Thanks for helping me。It work.

这边简单叙述一下，通过PadLocal Token到Python-Wechaty 跑通，希望对后来者有帮助。
Step1: 搭建PadLocal Token  Gateway
```
export WECHATY_LOG="verbose"
export WECHATY_PUPPET="wechaty-puppet-padlocal"
export WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal_XXXXXX"
export WECHATY_PUPPET_SERVER_PORT="9001"
export WECHATY_TOKEN="1fe5f846-3cfb-401d-b20c-XXXXX"

docker run -ti \
  --name wechaty_puppet_service_token_gateway \
  --rm \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_PADLOCAL_TOKEN \
  -e WECHATY_PUPPET_SERVER_PORT \
  -e WECHATY_TOKEN \
  -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
  wechaty/wechaty:0.56
```
WECHATY_TOKEN可以通过网站生成（https://www.uuidgenerator.net/version4），避免通远程服务器重复。
运行成功后，可以通过curl https://api.chatie.io/v0/hosties/1fe5f846-3cfb-401d-b20c-e03dd1974d9a

**Comment by huan** [comment]
@biofer Great to hear that your token gateway works with your Python Wechaty!

May I invite you to write a blog post for sharing your experiences to set up a token gateway with python wechaty? because would be greatly helpful for new developers who just start to use polyglot wechaty.

If you would like to, you can refer to .NET Wechaty post at <https://wechaty.js.org/2021/01/28/csharp-wechaty-for-padlocal-puppet-service/>

**Comment by biofer** [comment]
@huan It's my pleasure! The blog has been submitted.

**Comment by huan** [comment]
Awesome!

Could you please tell me that where have you submitted the blog?

I did not see it in https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_posts or any Pull Request.

**Comment by biofer** [comment]
@huan I  Pull Request in https://github.com/wechaty/wechaty.js.org.
Please let me know if there is any need to modify it.

**Comment by biofer** [comment]
@huan I have re Pull Request. All checks eventually  passed.
https://github.com/wechaty/wechaty.js.org/pull/660#issue-566816029

**Comment by wangzheooo** [comment]
总结了一下windows系统的搭建,
1.docker搭建好用拉取镜像
2.设置环境变量
WECHATY_LOG=verbose
WECHATY_PUPPET=wechaty-puppet-padlocal
ECHATY_PUPPET_PADLOCAL_TOKEN=puppet_padlocal_333333333333333
WECHATY_PUPPET_SERVER_PORT=8788
WECHATY_TOKEN="1fe5f846-3cfb-401d-b20c-XXXXX"
注:WECHATY_TOKEN是自己生成的uuid
3.打开cmd粘贴以下内容
`docker run -ti --name wechaty_puppet_service_token_gateway --rm -e WECHATY_LOG  -e WECHATY_PUPPET  -e WECHATY_PUPPET_PADLOCAL_TOKEN  -e WECHATY_PUPPET_SERVER_PORT  -e WECHATY_TOKEN -p %WECHATY_PUPPET_SERVER_PORT%:%WECHATY_PUPPET_SERVER_PORT%  wechaty/wechaty`
4.打开网站查一下
https://api.chatie.io/v0/hosties/1fe5f846-3cfb-401d-b20c-XXXXX

**Comment by atubo2012** [comment]
> 总结了一下windows系统的搭建,
> 1.docker搭建好用拉取镜像
> 2.设置环境变量
> WECHATY_LOG=verbose
> WECHATY_PUPPET=wechaty-puppet-padlocal
> ECHATY_PUPPET_PADLOCAL_TOKEN=puppet_padlocal_333333333333333
> WECHATY_PUPPET_SERVER_PORT=8788
> WECHATY_TOKEN="1fe5f846-3cfb-401d-b20c-XXXXX"
> 注:WECHATY_TOKEN是自己生成的uuid
> 3.打开cmd粘贴以下内容
> `docker run -ti --name wechaty_puppet_service_token_gateway --rm -e WECHATY_LOG -e WECHATY_PUPPET -e WECHATY_PUPPET_PADLOCAL_TOKEN -e WECHATY_PUPPET_SERVER_PORT -e WECHATY_TOKEN -p %WECHATY_PUPPET_SERVER_PORT%:%WECHATY_PUPPET_SERVER_PORT% wechaty/wechaty`
> 4.打开网站查一下
> https://api.chatie.io/v0/hosties/1fe5f846-3cfb-401d-b20c-XXXXX


THE QRCODE link is 404，Could you give mesome suggestion? Thanks!
![image](https://user-images.githubusercontent.com/30145089/109296602-8e598f80-786b-11eb-8a5f-2714ccd973d4.png)

**Comment by wangzheooo** [comment]
> > 总结了一下windows系统的搭建,
> > 1.docker搭建好用拉取镜像
> > 2.设置环境变量
> > WECHATY_LOG=verbose
> > WECHATY_PUPPET=wechaty-puppet-padlocal
> > ECHATY_PUPPET_PADLOCAL_TOKEN=puppet_padlocal_333333333333333
> > WECHATY_PUPPET_SERVER_PORT=8788
> > WECHATY_TOKEN="1fe5f846-3cfb-401d-b20c-XXXXX"
> > 注:WECHATY_TOKEN是自己生成的uuid
> > 3.打开cmd粘贴以下内容
> > `docker run -ti --name wechaty_puppet_service_token_gateway --rm -e WECHATY_LOG -e WECHATY_PUPPET -e WECHATY_PUPPET_PADLOCAL_TOKEN -e WECHATY_PUPPET_SERVER_PORT -e WECHATY_TOKEN -p %WECHATY_PUPPET_SERVER_PORT%:%WECHATY_PUPPET_SERVER_PORT% wechaty/wechaty`
> > 4.打开网站查一下
> > https://api.chatie.io/v0/hosties/1fe5f846-3cfb-401d-b20c-XXXXX
> 
> THE QRCODE link is 404，Could you give mesome suggestion? Thanks!
> ![image](https://user-images.githubusercontent.com/30145089/109296602-8e598f80-786b-11eb-8a5f-2714ccd973d4.png)

你画圈的上一行就是二维码内容,你找个二维码生成器,把上面那个网址链接生成二维码就行
