### ISSUE TITLE
PadLocal: Could you send me a token for padlocal test 

### ISSUE THREAD

**Issue by chuckfu** [wechaty/puppet-services#86]
Please make sure you have read the [Wechaty Puppet Service: PadLocal](https://wechaty.js.org/docs/puppet-services/padlocal/) from Wechaty Official Website before you continue writting this issue.

## Question
Could you send me a token for padlocal test

**Comment by padlocal** [comment]
@chuckfu Please send an email to oxddoxdd#gmail.com, then we can send you token related material.
