### ISSUE TITLE
Can we still get a long-term token:

### ISSUE THREAD

**Issue by paulhybryant** [wechaty/puppet-services#91]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
https://juzibot.wjx.cn/jq/80103105.aspx cannot be filled anymore

**Comment by huan** [comment]
@wechaty/juzi

**Comment by lijiarui** [comment]
Yes, you can get a long-term WeCom token if you join the contributor program, please feel free to contact me via WeChat(ruirui_0914) and send me the issue.

I will close this issue, feel free to create a new one if you still have any questions.
