### ISSUE TITLE
Paimon token not provided

### ISSUE THREAD

**Issue by paulhybryant** [wechaty/puppet-services#92]
Please make sure you have read the [Wechaty Puppet Service](https://wechaty.js.org/docs/puppet-services/) from Wechaty Official Website before you continue writting this issue.

## Question
https://wechaty.js.org/docs/puppet-services/paimon/

Registered with my phone number, but no trial token is provided.
I got one previously using a different phone number.

**Comment by zpaimon** [comment]
we don't provide trial token anymore.
