### ISSUE TITLE
PadLocal: how to buy a token? 

### ISSUE THREAD

**Issue by CashunterXie** [wechaty/puppet-services#94]
Please make sure you have read the [Wechaty Puppet Service: PadLocal](https://wechaty.js.org/docs/puppet-services/padlocal/) from Wechaty Official Website before you continue writting this issue.

## Question
how to buy a token? I am looking forword to hear from you

**Comment by padlocal** [comment]
@CashunterXie Please send an email to oxddoxdd#gmail.com , then we can send you token.
